{% set name = "mlip" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/ashapeev/mlip-2/-/archive/master/mlip-2-master.tar.gz
  sha256: ae4c78cba93f84b274af779e26319e3f5b4ba5305cef0e0c0f111b6b82cf2d40

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make 
  host:
    - libcblas
    - {{ mpi }}
  run:

about:
  home: https://mlip.skoltech.ru
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Machine Learning of Interatomic Potentials (MLIP)'
  description: |
    Machine Learning of Interatomic Potentials (MLIP) is a software
    being developed and mainted by the group of Alexander Shapeev 
    (Skoltech).
  doc_url: https://gitlab.com/ashapeev/mlip-1-legacy
  dev_url: https://mlip.skoltech.ru/documentation/

extra:
  recipe-maintainers:
    - jan-janssen
