{% set name = "mlip" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url:  https://gitlab.com/ashapeev/mlip-3/-/archive/main/mlip-3-main.tar.gz
  sha256: 27191ea9b54a417f17f41dd05dbef8c8f85f7a351b5567c961372287247402e9
  patches:
    - openblas.patch
    - make.patch

build:
  number: 0
  skip: true  # [win or osx and mpi == 'mpich']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make 
  host:
    - libcblas
    - {{ mpi }}
  run:

about:
  home: https://mlip.skoltech.ru
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Machine Learning of Interatomic Potentials (MLIP)'
  description: |
    Machine Learning of Interatomic Potentials (MLIP) is a software
    being developed and mainted by the group of Alexander Shapeev 
    (Skoltech).
  doc_url: https://gitlab.com/ashapeev/mlip-1-legacy
  dev_url: https://mlip.skoltech.ru/documentation/

extra:
  recipe-maintainers:
    - jan-janssen
